### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#102]
Acceptance criteria:
- FAQ page [as per design](https://www.dropbox.com/s/iu5znibbi1h4fly/FAQ.png?dl=0).
- 'ALPHA VERSION' link in footer navigates to 'When will the site be ready' question. Page must scroll to this specific question.
- 'Learn More' button on homepage navigates to 'What is Fifthweek?' question. Page must scroll to this specific question.

**Comment by ttbarnes** [comment]
'ALPHA VERSION' purely links to the faq page instead of the 'when will the site be ready' question, since it's the first question :)

'Learn More' is linked up to a specific section in FAQ.

**Comment by ljwagerfield** [comment]
As mentioned, we'll remove the 'jump to' functionality until we can find a better solution to emulate anchor tags.
