### ISSUE TITLE
Configure landing page (styling)

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#105]
Acceptance criteria:
- Customise Landing Page, as per designs: 
  - `Creator MVP / Landing Page (Basics)`
  - `Creator MVP / Landing Page (Header Image)`
  - `Creator MVP / Landing Page (Full Description)`

**Comment by ttbarnes** [comment]
I'm happy with this. Would be good to have a fresh pair of eyes go over it.

**Comment by ljwagerfield** [comment]
Great work!

My only comment so far: the channels are a multi-select list, where the first item must always be selected, so a disabled checked state is probably most appropriate. 

The idea is subscribers always get access to the base-channel, but they can bolt-on extra channels in any combination they like. The total price displayed in the blue button must be a sum of all these prices.

**Comment by ttbarnes** [comment]
Righto thanks Lawrence!

That makes a lot more sense. I'll update :-)

**Comment by ljwagerfield** [comment]
Sorry, just realised I'm leaving feedback for the wrong thing! Will have a look at this now :)

**Comment by ljwagerfield** [comment]
This page also looks great, nice work :+1:
