### ISSUE TITLE
Centrally align container

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#108]
Acceptance criteria:
- Resize browser beyond container's max-width (1100px).
- Container centers, like on the [hi.co website](https://hi.co/).
- Container takes is center from the right edge of the sidebar (or the left edge of screen if collapsed), and the right edge of the screen.

**Comment by ttbarnes** [comment]
Discussed with Lawrence - this is good now.

We have a max-width in place, and instead of centralising the containers on large screens, we will left align. Would be good to revisit this at a later date, with everything centralised and a more lightweight sidebar.
