### ISSUE TITLE
Do we want to remove the # from urls?

### ISSUE THREAD

**Issue by jamesthurley** [fifthweek/fifthweek-web#11]
See the following for some pros and cons:

http://stackoverflow.com/questions/14771091/removing-the-hashtag-from-angularjs-urls-symbol

**Comment by ljwagerfield** [comment]
Would could have the following rules, assuming we find a way suitable way for supporting older browsers:
```
https://www.fifthweek.com/p/{tail} => https://www.fifthweek.com/#{tail}
https://www.fifthweek.com/{creator} => https://www.fifthweek.com/#creator={creator}
```

**Comment by jamesthurley** [comment]
It is done.
