### ISSUE TITLE
File upload (API)

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#122]
New service for persisting uploaded files.

Acceptance criteria:

- New service endpoint: accepts file uploads.
  - Persists posted file.
  - Creates new entry in `GeneratedAssets` table.
    - Set `generation date` to today (UTC+0).
    - Set `mime type` field to value from `content-type` header.
  - Create new entry in `UserUploads` table.
    - Set `user ID` to current user.
    - Set weak cross reference (no referential integrity) to `GeneratedAssets`. Asset may be garbage collected later, but we still want to track the event of the user uploading for audit (I believe!).
  - Return ID to new generated asset.

**Comment by jamesthurley** [comment]
Currently following the example here:

http://www.mono-software.com/blog/post/Mono/233/Async-upload-using-angular-file-upload-directive-and-net-WebAPI-service/

Also shows the angular side.
