### ISSUE TITLE
Compose first post notification

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#129]
Acceptance criteria:
- All post types (note, image and file) must contain a notification above the main form for creators with no posts, as per design: `Creator MVP / Compose Note (First)`.

**Comment by ljwagerfield** [comment]
I was about to pick this up, but thought I'd defer until we have some Protractor tests for the existing functionality :+1:

**Comment by jamesthurley** [comment]
Purged
