### ISSUE TITLE
Backlog (styling)

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#130]
Acceptance criteria:
- Backlog, as per design: `Creator MVP / Backlog`
- We need some way of sorting queued posts. Drag-and-drop?

**Comment by ttbarnes** [comment]
Thinking of using angular-ui-sortable for the sorting, eg: http://jsfiddle.net/whippy/bwq82bvs/show/

**Comment by ttbarnes** [comment]
Ready:
- template
- dummy data with conditionals
- toggles/switches for comment/favourite icons
- drop down toggle & menu for '...'  (might want to add an arrow)
- draggable, re-orderable items 

We need to think about the timers/countdowns.
