### ISSUE TITLE
Creator vanity URL redirect

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#133]
Acceptance criteria:
- The following URL pattern:
   `https://www.fifthweek.com/{creator}`

  Redirects to:
  `https://www.fifthweek.com/#creator?username={creator}`

**Comment by ljwagerfield** [comment]
Moving to post-MVP since we are faking this for MVP.

**Comment by jamesthurley** [comment]
Don't think this is needed anymore as we have vanity urls now (without needing to redirect).
