### ISSUE TITLE
Replace twitter bootstrap with ui-bootstrap

### ISSUE THREAD

**Issue by ttbarnes** [fifthweek/fifthweek-web#142]
Currently we're using default bootstrap that utilises jquery and compass.

ui-bootstrap uses nice angular components: http://angular-ui.github.io/bootstrap/

Acceptance criteria (tbc):
- Default bootstrap is removed (js components and css)
- Compass is replaced (somehow?)
- Grunt build works with new compass instance 
- Only the necessary angular ui components are included in the build (currently, purely modal)

**Comment by ttbarnes** [comment]
Bootstrap css and bootstrap-sass-official js no longer injected into index.html, via Grunt:
```
wiredep: {
      app: {
        src: ['<%= yeoman.app %>/index.html'],
        ignorePath:  /\.\.\//,
        exclude: [
          'bower_components/bootstrap/dist/css/bootstrap.css',
          'bower_components/bootstrap-sass-official/assets/javascripts/*'
        ]
      },
```

Uninstalling bootstrap-sass-official via bower causes grunt to go crazy. I think there's a lot of tasks dependant on this, and maybe compass, from yeoman generation. 

Need to look at this further, but for now, at least the compilation is not bloated with unnecessary bootstrap versions which is the main aim for SP-2. We now purely have:
- sass-official-bootstrap imported via sass `@import`
- ui-bootstrap JS injected into `index.html` via grunt bower/wiredep task.

**Comment by ttbarnes** [comment]
Note: found an issue with grunt `:dist` task - font awesome was not included.

I've moved FA fonts and stylesheets into custom directories (copied from bower components) which is imported with sass.

**Comment by jamesthurley** [comment]
Purged
