### ISSUE TITLE
Add task cancellation

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#144]
We do not currently implement `CancellationTokens` in our command handlers.

Regarding cancellation in general:

A common pattern is to create a `Deadline` object for each command, which states some point in the future at which the command will be cancelled and a message will be sent to the user. These are typically defined upfront and associated with the command object. This expiry is usually gauged off how long the user can be expected to wait for an operation (so on a Web app, that's usually quite short!).

After the deadline has expired, the cancellation token should be raised. Furthermore, if a handler receives a command that has an expired deadline, it should discard it.

**Comment by jamesthurley** [comment]
Purged
