### ISSUE TITLE
Ability to link in-page links

### ISSUE THREAD

**Issue by ttbarnes** [fifthweek/fifthweek-web#145]
eg 'myPage#something'.

**Comment by ttbarnes** [comment]
Found a half decent solution. It's not amazing, but does the trick.

Define a state with ui-router - must include a controller:
```
.state('help.faq.learnmore', {
  url: '#learn-more',
  controller: 'faqCtrl'
})
```

Then we return the hash fragment with `$location`, and fire `$anchorScroll`, which scrolls to the element.
````
$scope.onEnter = function anchorScroll(){
  $location.hash('learn-more');
  $anchorScroll();
};
```

If we begin to have a lot more in page links, we can look for a better approach.

**Comment by ttbarnes** [comment]
As discussed, moving this back into the backlog.

**Comment by jamesthurley** [comment]
Purged
