### ISSUE TITLE
URLs should contain context

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#146]
We currently have several places where we're inferring context from session state:

`subscriptions/currentCreatorStatus`

This is not particularly RESTful, since resources should be discriminated through URLs as opposed to some hidden state. Practically speaking, including context in URLs simplifies caching and logging:

`creators/{creatorId}/status`

In the above case, we would still apply the same security checks to make sure that user has access to that resource.

**Comment by jamesthurley** [comment]
Purged
