### ISSUE TITLE
Move code generation into compiled project and use Roslyn

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#148]
Code generation is currently compiled on-run. The codebase for this has grown, so should be moved into its own project using compiled class files.

There is also a new way of interacting with the code model a bit more intelligently:

http://blogs.msdn.com/b/ericlippert/archive/2012/06/05/announcing-microsoft-roslyn-june-2012-ctp.aspx

**Comment by jamesthurley** [comment]
Purged
