### ISSUE TITLE
Title bar misbehaves when resizing and scrolling

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#151]
Reproduction steps:
- Load the site.
- Go to FAQ page.
- Resize your browser in any dimension.
- Notice the navbar now appears (it was previously above the fold).
- Now scroll upwards: the navbar stays fixed in middle of page, overlaying content.

**Comment by jamesthurley** [comment]
Can't reproduce, seems to be resolved.
