### ISSUE TITLE
Refreshing the FAQ page takes you back to homepage

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#152]
Reproduction steps:
- Load site
- Go to FAQ page (through 'learn more' link)
- Refresh page
- Notice how you're now back at the homepage

**Comment by ttbarnes** [comment]
Good find @ljwagerfield 

Looking into this - this thread may help: https://github.com/angular-ui/ui-router/issues/105

**Comment by ttbarnes** [comment]
Good find @ljwagerfield - Looking into this

**Comment by ttbarnes** [comment]
Fixed! Forgot to include this character... `^`
