### ISSUE TITLE
Use headless browser for Protractor tests in development

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#162]
This would speed up Protractor tests running locally, which we currently do before each push.

Justification is: we're currently only testing on one browser as it is, knowing that BrowserStack will do the full testing. Therefore, that one browser may as well be a headless browser.

**Comment by ljwagerfield** [comment]
https://github.com/angular/protractor/issues/1512

**Comment by ljwagerfield** [comment]
Played around with this for an hour. Current versions of Protractor/Selenium/PhantomJS in the NPM repository are not compatible with one-another. 

Leaving this until the PhantomJS is updated to not use deprecated Selenium features.

**Comment by jamesthurley** [comment]
@ljwagerfield Does this still need doing now that protractor is running much faster?

**Comment by jamesthurley** [comment]
Purged
