### ISSUE TITLE
Conflate error messages sent to developers

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#166]
One email communicates the severity of an error as much as 100 emails, which is what I received by accessing our site with a double `//` in the URL.

We can always include the occurrences since last conflation in the log message. E.g. 

```
Fifthweek.Api.Core.ExternalErrorException: {  
  "occurrences": 100, 
  "message": 
  "Uncaught ReferenceError: angular is not defined", 
  "source": "http://localhost:9000//scripts/services/authenticationservice.js", 
  "url": "http://localhost:9000//#/creators/landing-page", 
  "line": "3", 
  "column": "1" }
```

Tempted to make this a pre-MVP thing, else we could end up DOSing ourselves if we get 100 emails per error.

**Comment by ttbarnes** [comment]
:+1:

**Comment by ljwagerfield** [comment]
Moving to post-MVP. We'll most likely prioritise this when the first wave of errors start pouring in.

**Comment by jamesthurley** [comment]
Purged
