### ISSUE TITLE
Ability to define a body page class instead of using non-dev titles

### ISSUE THREAD

**Issue by ttbarnes** [fifthweek/fifthweek-web#167]
Acceptance criteria:
- Via ui-router `data:{}` config, an optional body class can be defined for any page.
- HTML body class will use `pageTitle` (as is in place now), but if `bodyTitle` is defined, this will be used instead.

**Comment by jamesthurley** [comment]
@ttbarnes Just came across this issue referenced in the customise landing page HTML.  If I understand it correctly, I think it's resolved (other than defaulting to the page title, which I removed).  Can you confirm?

**Comment by ttbarnes** [comment]
@jamesthurley Yes this is good now, little out of date. We should only define the body class if we have to - more flexible this way too. Closing.
