### ISSUE TITLE
Add trash channel

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#193]
Add a hidden channel to receive deleted collections. This provides easier recovery for accidental mass deletions. This may also require us to update the `Subscriptions` table to have two nullable foreign keys to track these special channels: `DefaultChannelId` and `TrashChannelId`.

Hard deletes are fine for now, as we ensure a low likelihood of accidental deletions through the UI. However, when we open up the API to third parties, we cannot guarantee how good their UI will be around potential deletions, so soft deleting becomes more important.

**Comment by jamesthurley** [comment]
Just a note that since this was created moving posts between channels has become more involved, as it will require moving all blobs to the new channel's blob container as well.

**Comment by jamesthurley** [comment]
Purged
