### ISSUE TITLE
Separate routes from app.js

### ISSUE THREAD

**Issue by ttbarnes** [fifthweek/fifthweek-web#194]

**Comment by jamesthurley** [comment]
@ttbarnes, if you take a look at issue #12 there is a link to an example angular application on GitHub which has everything organised into modules.  What do you think of the structure there?  I realise it's a bit more broad than simply separating routes from app.js but thought I'd bring it up.

**Comment by ttbarnes** [comment]
looks great @jamesthurley , i'm all for that - the more modular the better I think.
