### ISSUE TITLE
Investigate failover for API

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#196]
We experienced our first hour of outage this morning, which means extra steps need to be taken to increase availability.

Hosting `fifthweek-web` on an edge network like AWS CloudFront will solve this problem for the front-end components.

However, we still need to consider failover options for `fifthweek-api`.

**Comment by jamesthurley** [comment]
@ljwagerfield Can I close this off?  I think since this was created we've done more research and are probably happy it's something for the future?

**Comment by jamesthurley** [comment]
Purged
