### ISSUE TITLE
Custom rows/columns framework

### ISSUE THREAD

**Issue by ttbarnes** [fifthweek/fifthweek-web#198]

**Comment by ttbarnes** [comment]
I have some things we can use for this :-)

**Comment by ljwagerfield** [comment]
This will be encompassed in the post-MVP redesign once we secure funding. By this point, we will have the bandwidth the remove Bootstrap altogether.

However, for now we need to use Bootstrap's conventional mechanisms for achieving layout, working with the framework as outlined in their documentation.

**Comment by ttbarnes** [comment]
Yes, but note that it's impossible or painful to achieve some things without overriding, or doing non-bootstrap things. There are some examples in the sass already :+1:
