### ISSUE TITLE
Mobile header nav scrolling

### ISSUE THREAD

**Issue by ttbarnes** [fifthweek/fifthweek-web#199]
Something elegant.

**Comment by ttbarnes** [comment]
Could maybe use a similar approach to this: http://hugogiraudel.com/2013/08/23/scroll-overflow-menu/

**Comment by ttbarnes** [comment]
Working well on mobile although doesn't look v.nice on small desktop sizes (as discussed). Tested on iOS, all seems good. Ideally we can test this in a device lab.

**Comment by ljwagerfield** [comment]
Good work dude - all the more important now that we have longer secondary nav titles. As an aside, we may decide we want shorter titles for mobile just to increase the number of links that gets included within the horizontal fold. Post-MVP though.

**Comment by ttbarnes** [comment]
Cheers, sounds good - always good to be simpler/less-words.
