### ISSUE TITLE
Improve blob download speed

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#235]
The following two sample images have similar sizes.

FW on Azure: https://fifthweekdev.blob.core.windows.net/public/Zs95YMv9EeSCgAAcQnE6cQ2/3000x800-crop?sv=2014-02-14&sr=c&sig=nE7rvoqvTio8Kov9C4sfFhLIjkEdeR819rso51rCLYc%3D&se=2015-03-17T18%3A17%3A03Z&sp=r

Hi.co: https://i.hi.co/media/images/cover/5508183a7480b4b4258b45a3.jpg

The Fifthweek image takes approximately 7x longer to load.

**Comment by jamesthurley** [comment]
Now using Azure CDN.
