### ISSUE TITLE
Improve AutoFac composition 

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#29]
Will allow more code to be written as separate classes to promote SRP. Will also allow decorators to be applied to certain usage sites and not others (see example below for clarification).

Acceptance criteria:
- Conventional controllers/queries/commands must be added in a way that requires no extra config (currently supported).
- Exceptional configuration must be possible. Examples:
  - Add 2 type-specific decorators at different points in a query handler, say before and after the standard transactional decorator.
  - Inject a specific decorator setup to certain components, say user-input validation and normalisation for commands used by client-facing components such as controllers.

**Comment by jamesthurley** [comment]
This has been done as part of other tasks now.
