### ISSUE TITLE
The user should not be able to press the register or sign-in button twice.

### ISSUE THREAD

**Issue by jamesthurley** [fifthweek/fifthweek-web#51]
Perhaps a busy indicator should be displayed instead.

Acceptance criteria:

 - The user should only be able to click the relevant button once

**Comment by ljwagerfield** [comment]
Tried the above. Bypasses validation. Now trying the second answer with the higher rating that just ties the 'disabled' state to the 'pending' property :)

**Comment by ljwagerfield** [comment]
Have committed the above solution to `master` - small change so shouldn't cause you much of a merge issue @ttbarnes. 

I've also added some Protractor tests, which I've disabled by default as they're not working as expected. Have posted a Q on StackOverflow.
