### ISSUE TITLE
Analytics end-to-end testing

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#77]
Acceptance criteria:
- Assert 'page view' is tracked to GA and KISSmetrics on each page load.
- Assert 'campaign data' is tracked to GA and KISSmetrics on initial site visit.
- Assert 'last opened email from' is tracked to KISSmetrics on initial site visit.
- Assert 'set user' is tracked to GA and KISSmetrics when signing in and registering.
- Assert 'clicked "become a creator"' is tracked to GA and KISSmetrics.
- Assert 'clicked "send feedback"' is tracked to GA and KISSmetrics.
- Assert 'video played/paused/finished' is tracked to GA and KISSmetrics on both videos.

**Comment by jamesthurley** [comment]
Purged
