### ISSUE TITLE
Re-styled sidebar

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#86]
Acceptance criteria:
- Sidebar styled [as per design] (https://www.dropbox.com/s/jub07kml2lqtqme/FAQ.png?dl=0).
- Contains following links:
  - Authenticated state: 
    - '{username}' primary link. Drops-down to display 'Sign out' link. See ['My Account' design](https://www.dropbox.com/s/6bygnncnwdy04zi/Account-Settings.png?dl=0).
    - 'Dashboard' primary link. Drops-down to display 'Quick demo' and 'Feedback'. Appears in separate link group (see example of 'News Feed' link in existing designs).
  - Unauthenticated state:
    - 'Register' and 'Sign In' links. See ['Register' design](https://www.dropbox.com/s/0a1e2pw69a3swr0/Register.png?dl=0).
- Fifthweek link takes you home `/`.
- Sidebar expanded by default on MD and LG devices (with exception to homepage).
- Sidebar collapsed by default on XS and SM devices.
- Sidebar collapsed by default on homepage on all devices.
- Clicking primary links with child pages causes that link to expand, dropping down a list of the child pages. Such primary pages will not exist as their own page.

**Comment by ttbarnes** [comment]
For now, we're de-scoping auto-collapsing the sidebar in the home page. We can look at this later, and build a solution so that such a feature can be easily applied to any view.
