### ISSUE TITLE
Update colours

### ISSUE THREAD

**Issue by ljwagerfield** [fifthweek/fifthweek-web#97]
Acceptance criteria:
- Colours [as per design](https://www.dropbox.com/s/mpin6pvjmfq2i91/Landing-Page-%28Basics%29.png?dl=0).
- Background: #f9f9f9
- Text (default): #555459
- Headings: #3d4b5b
- Links: #439fe0
- Sidebar text: #f8f9fa
- Sidebar footer text: #b1b7bd
- Sidebar footer links: #ccd0d3

**Comment by ttbarnes** [comment]
Colours updated. Some of the hex codes mentioned here differ from the design, so i've used the design in these instances.
